[settings]
disable_backends = ["asdf", "vfox"]

[settings.pipx]
uvx = true

[tools]
go = "latest"
java = "latest"
maven = "latest"
aws = "latest"

# [Node.js]
node = "lts"
"npm:aws-cdk" = "latest"
"npm:@openai/codex" = "latest"
"npm:agent-browser" = "latest"

# [Python]
python = "3.13"
"pipx:snowflake-cli" = "latest"

# [Rust]
rust = "latest"
"cargo:keifu" = "latest"
"cargo:filetree" = "latest"
